### ISSUE TITLE
Install compression library before 'ant debug'

### ISSUE THREAD

**Issue by doble-d** [tube42/flappybalt-love2d#1]
Maybe you could add before running `ant debug` in part two to install a 32 bit runtime compression library to avoid running into a build failure:

https://stackoverflow.com/questions/22701405/aapt-ioexception-error-2-no-such-file-or-directory-why-cant-i-build-my-grad

> Cannot run program "/usr/local/android-sdk-linux/build-tools/19.0.3/aapt": error=2, No such file or directory

`sudo apt install lib32stdc++6 lib32z1`

**Comment by tube42** [comment]
This looks familiar, but I think it is one of those commands that differs depending on distro version.

What ubuntu version are you using?

**Comment by tube42** [comment]
This is an android/google issue anyway, not related to love2d so i am going to close it
